version: '3'
services:
  jmdb2ldap:
    container_name: jmdb2ldap
    image: jenkinsluckev/db2ldap:${JMDB2LDAP_BUILD_TYPE:-local}
    restart: always
    volumes:
      - jmdb2ldap-secrets:/var/data/secrets/jmdb2ldap
      - certbot-conf:/var/data/certbot-conf:ro
volumes:
  jmdb2ldap-secrets:
    external: true
  certbot-conf:
    external: true
networks:
  default:
    external:
      name: jenkins
  jenkins:
    external: true